/* VYRO Studios — content, routing and interaction layer. Edit the data blocks first. */
const siteConfig={brandName:"VYRO Studios",tagline:"VISUALS THAT MOVE.",founder:"Denis",accent:"#d8ff3e",contact:{phone:"0730 062 060",whatsapp:"40730062060",email:"vyrostudioos@gmail.com",facebook:"https://www.facebook.com/profile.php?id=61594069011944",tiktok:"https://www.tiktok.com/@vyrostudios2?lang=en",instagram:"https://www.instagram.com/vyrostudioos/"},vision:["Storytelling","Visual quality","Attention to detail","Constant learning","Experimentation","Creative growth"]};
const projects=[
{id:1,title:"DaVinci Resolve 20 — Editing Workspace",category:"video",year:"2026",thumbnail:"assets/images/DaVinci-Resolve-20-Edit.webp",description:"A look at the editing workspace and creative environment used for VYRO Studios work in DaVinci Resolve 20.",role:"Video Editor",tools:["DaVinci Resolve"],beforeImage:"",afterImage:""},
{id:2,title:"Car Poster",category:"graphic design",year:"2026",thumbnail:"assets/images/CarPoster.webp",description:"Cinematic automotive poster focused on composition, atmosphere and visual impact.",role:"Graphic Designer",tools:["Adobe Photoshop"],beforeImage:"",afterImage:""}
];
const services=[["VIDEO EDITING","Short-form content, social media videos, cinematic edits and storytelling."],["PHOTO EDITING","Photo manipulation, retouching, compositing and creative image editing."],["THUMBNAIL DESIGN","YouTube thumbnails and attention-focused visual designs."],["MOTION DESIGN","Kinetic typography, animated graphics, transitions and motion visuals."],["GRAPHIC DESIGN","Posters, artwork, promotional graphics and digital visuals."],["VISUAL EFFECTS","Creative effects, compositing and visual enhancement."],["COLOR GRADING","Color correction, cinematic grading and visual consistency."],["SOUND DESIGN","Audio editing, sound effects and visual-audio synchronization."],["SOCIAL MEDIA CONTENT","Platform-ready visual content built around the pace and language of social media."]];
const skills=[{name:"EDITING",items:[["DaVinci Resolve","Advanced"],["Video Editing","Advanced"]]},{name:"PHOTO",items:[["Adobe Photoshop","Advanced"],["Photo Editing","Advanced"]]},{name:"DESIGN",items:[["Thumbnail Design","Advanced"],["Graphic Design","Advanced"],["Photo Manipulation","Advanced"]]},{name:"MOTION",items:[["Motion Design","Advanced"],["Visual Effects","Advanced"]]},{name:"COLOR",items:[["Color Correction","Advanced"],["Color Grading","Advanced"]]},{name:"AUDIO",items:[["Sound Design","Advanced"],["Audio Editing","Advanced"]]}];
const categoryLabels={all:"All",video:"Video",photo:"Photo",thumbnails:"Thumbnails",motion:"Motion",vfx:"VFX","graphic design":"Graphic Design"};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],reduceMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;let activeFilter="all",lastFocusedElement=null,currentView="home";
function escapeHtml(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function escapeAttr(v=""){return escapeHtml(v)}function safeText(v,f="Not specified"){return v==null||v===""?f:String(v)}function phoneDigits(v){return String(v||"").replace(/\D/g,"")}function imageFallback(t){return `<div class="media-fallback"><span>VYRO / VISUAL</span><strong>${escapeHtml(t||"Untitled")}</strong><small>Asset coming soon</small></div>`}
function initConfig(){document.documentElement.style.setProperty("--accent",siteConfig.accent);document.title=`${siteConfig.brandName} | Creative Editing & Visual Design`;$("#current-year").textContent=new Date().getFullYear()}
function initDynamicContent(){
 $("#vision-list").innerHTML=siteConfig.vision.map(v=>`<li>${escapeHtml(v)}</li>`).join("");
 $("#services-list").innerHTML=services.map(([t,d],i)=>`<article class="service-row reveal-up"><span class="service-index">${String(i+1).padStart(2,"0")}</span><h3>${escapeHtml(t)}</h3><p>${escapeHtml(d)}</p><span class="service-arrow" aria-hidden="true">↗</span></article>`).join("");
 $("#skills-grid").innerHTML=skills.map((g,i)=>`<article class="skill-group reveal-up"><div class="skill-heading"><span>0${i+1}</span><h3>${escapeHtml(g.name)}</h3></div><div>${g.items.map(([n,l])=>`<div class="skill-item"><span>${escapeHtml(n)}</span><span class="skill-level">${escapeHtml(l)}</span></div>`).join("")}</div></article>`).join("");
}
function initFilters(){const filters=["all","video","photo","thumbnails","motion","vfx","graphic design"];$("#portfolio-filters").innerHTML=filters.map(f=>`<button class="filter-button ${f===activeFilter?"active":""}" type="button" data-filter="${escapeAttr(f)}" aria-pressed="${f===activeFilter}">${escapeHtml(categoryLabels[f])}</button>`).join("");$$('.filter-button').forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;$$('.filter-button').forEach(x=>{const on=x.dataset.filter===activeFilter;x.classList.toggle("active",on);x.setAttribute("aria-pressed",String(on))});renderProjects()}))}
function renderProjects(){const root=$("#portfolio-grid"),empty=$("#portfolio-empty");if(!root)return;const filtered=activeFilter==="all"?projects:projects.filter(p=>String(p.category).toLowerCase()===activeFilter);empty.hidden=filtered.length>0;root.innerHTML=filtered.map(p=>{const image=p.thumbnail?`<img src="${escapeAttr(p.thumbnail)}" alt="${escapeAttr(p.title)}" loading="lazy" decoding="async">${p.id===1?`<span class="davinci-blur-half" style="--blur-image:url(\'${escapeAttr(p.thumbnail)}\')" aria-hidden="true"></span>`:""}`:imageFallback(p.title);const specialClass=p.id===1?" project-davinci":p.id===2?" project-poster":"";return `<article class="project-card${specialClass} reveal-up" tabindex="0" role="button" data-project-id="${escapeAttr(p.id)}" aria-label="View ${escapeAttr(p.title)}"><div class="project-media">${image}<span class="project-number">${String(p.id).padStart(2,"0")}</span></div><div class="project-info"><div class="project-top"><span>${escapeHtml(categoryLabels[String(p.category).toLowerCase()]||p.category)}</span><span>${escapeHtml(p.year)}</span></div><div class="project-bottom"><div><h3>${escapeHtml(p.title)}</h3><span class="project-cta">View project <span>↗</span></span></div><span class="eyebrow">${escapeHtml(p.role)}</span></div></div></article>`}).join("");
 $$('img',root).forEach(img=>img.addEventListener("error",()=>img.replaceWith(document.createRange().createContextualFragment(imageFallback(img.alt))),{once:true}));$$('.project-card',root).forEach(card=>{card.addEventListener("click",()=>openProject(Number(card.dataset.projectId)));card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openProject(Number(card.dataset.projectId))}})});observeReveals(root);initHoverStates(root)}
function metaItem(l,v){return `<div><span>${escapeHtml(l)}</span><strong>${escapeHtml(v)}</strong></div>`}
function openProject(id){const p=projects.find(x=>Number(x.id)===Number(id));if(!p)return;const modal=$("#project-modal"),media=$("#modal-media");$("#modal-category").textContent=`${categoryLabels[String(p.category).toLowerCase()]||safeText(p.category)} / ${safeText(p.year)}`;$("#modal-title").textContent=safeText(p.title);$("#modal-description-text").textContent=safeText(p.description);$("#modal-meta").innerHTML=metaItem("Role",safeText(p.role))+metaItem("Year",safeText(p.year))+metaItem("Tools",Array.isArray(p.tools)&&p.tools.length?p.tools.join(", "):"Not specified");media.innerHTML="";if(p.thumbnail){const img=document.createElement("img");img.src=p.thumbnail;img.alt=p.title;img.loading="eager";img.decoding="async";img.addEventListener("error",()=>media.innerHTML=imageFallback(p.title),{once:true});media.appendChild(img);if(p.id===1){const blur=document.createElement("span");blur.className="modal-davinci-blur";blur.style.setProperty("--blur-image",`url("${p.thumbnail}")`);blur.setAttribute("aria-hidden","true");media.appendChild(blur)}}else media.innerHTML=imageFallback(p.title);if(p.beforeImage&&p.afterImage)media.insertAdjacentHTML("beforeend",buildBeforeAfter(p));lastFocusedElement=document.activeElement;modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");$(".modal-close").focus()}
function buildBeforeAfter(p){return `<div class="before-after" data-before-after><img src="${escapeAttr(p.beforeImage)}" alt="Before ${escapeAttr(p.title)}"><div class="after-layer"><img src="${escapeAttr(p.afterImage)}" alt="After ${escapeAttr(p.title)}"></div><input type="range" min="0" max="100" value="50" aria-label="Before and after comparison"></div>`}function closeProject(){const m=$("#project-modal");m.classList.remove("open");m.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open");$("#modal-media").innerHTML="";if(lastFocusedElement?.focus)lastFocusedElement.focus()}
function initModal(){ $("#project-modal").addEventListener("click",e=>{if(e.target.matches("[data-close-modal]"))closeProject()});document.addEventListener("keydown",e=>{const m=$("#project-modal");if(!m.classList.contains("open"))return;if(e.key==="Escape"){closeProject();return}if(e.key==="Tab"){const f=$$('button,a,input,[tabindex]:not([tabindex="-1"])',m).filter(x=>!x.disabled&&x.offsetParent!==null);if(!f.length)return;const [a,b]=[f[0],f[f.length-1]];if(e.shiftKey&&document.activeElement===a){e.preventDefault();b.focus()}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a.focus()}}});document.addEventListener("input",e=>{const s=e.target.closest("[data-before-after] input[type=range]");if(!s)return;const layer=s.closest("[data-before-after]")?.querySelector(".after-layer");if(layer)layer.style.width=`${s.value}%`})}
function initContact(){const c=siteConfig.contact, cards=[{key:"facebook",icon:"f",title:"FACEBOOK",desc:"Connect with me",value:"Facebook",href:c.facebook},{key:"tiktok",icon:"♪",title:"TIKTOK",desc:"Follow the work",value:"TikTok",href:c.tiktok},{key:"instagram",icon:"◎",title:"INSTAGRAM",desc:"Follow the work",value:"Instagram",href:c.instagram},{key:"phone",icon:"⌕",title:"PHONE",desc:"Project contact",value:c.phone,href:"#order"}];$("#contact-grid").innerHTML=cards.map(card=>{const available=Boolean(card.href),tag=available?`<a class="contact-card reveal-up" href="${escapeAttr(card.href)}" ${card.href.startsWith("http")?'target="_blank" rel="noopener noreferrer"':''}>`:`<div class="contact-card unavailable reveal-up" aria-disabled="true">`;return `${tag}<span class="contact-icon" aria-hidden="true">${escapeHtml(card.icon)}</span><div><h3>${escapeHtml(card.title)}</h3><p>${escapeHtml(card.desc)}</p><span class="contact-value">${escapeHtml(card.value)}</span></div><span class="contact-arrow">${available?"↗":"—"}</span></${available?"a":"div"}>`}).join("");observeReveals($("#contact-grid"));initHoverStates($("#contact-grid"))}
function setMenu(open){const t=$(".menu-toggle"),m=$("#mobile-menu");t.setAttribute("aria-expanded",String(open));t.setAttribute("aria-label",open?"Close menu":"Open menu");m.classList.toggle("open",open);m.setAttribute("aria-hidden",String(!open));document.body.classList.toggle("menu-open",open)}
function initOrder(){const form=$("#order-form"),status=$("#order-status"),success=$("#order-success"),submit=$("#order-submit"),urlField=$("#order-url");if(!form)return;urlField.value=location.href.split("#")[0]+"#order";const phoneOk=v=>{const d=String(v||"").replace(/\D/g,"");return d.length>=9&&d.length<=15};form.addEventListener("submit",async e=>{e.preventDefault();status.textContent="";status.className="form-status";if(!form.reportValidity())return;const phone=form.elements.phone.value;if(!phoneOk(phone)){form.elements.phone.setCustomValidity("Please enter a valid phone number.");form.elements.phone.reportValidity();form.elements.phone.setCustomValidity("");return}submit.disabled=true;submit.setAttribute("aria-busy","true");submit.querySelector("span").textContent="…";status.textContent="Delivering request…";try{const data=Object.fromEntries(new FormData(form).entries());delete data._honey;const res=await fetch("https://formsubmit.co/ajax/vyrostudioos@gmail.com",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(data)});const result=await res.json().catch(()=>({}));if(!res.ok||result.success===false)throw new Error(result.message||"Submission failed");form.hidden=true;success.hidden=false;status.textContent="";success.scrollIntoView({behavior:reduceMotion?"auto":"smooth",block:"center"});observeReveals(success);initMagnetic()}catch(err){status.textContent="We couldn't deliver the request right now. Please try again in a moment.";status.classList.add("error")}finally{submit.disabled=false;submit.removeAttribute("aria-busy");submit.querySelector("span").textContent="↗"}})}
function initHeader(){const header=$("#site-header");$$('[data-route]').forEach(a=>a.addEventListener("click",()=>setMenu(false)));$(".menu-toggle").addEventListener("click",()=>setMenu($(".menu-toggle").getAttribute("aria-expanded")!=="true"));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$(".menu-toggle").getAttribute("aria-expanded")==="true")setMenu(false)});let ticking=false;window.addEventListener("scroll",()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{header.classList.toggle("scrolled",scrollY>24);const max=document.documentElement.scrollHeight-innerHeight;$(".scroll-progress").style.transform=`scaleX(${max>0?scrollY/max:0})`;ticking=false})},{passive:true})}
function routeFromHash(){const raw=location.hash.replace(/^#/,"").toLowerCase();return ["home","work","about","services","skills","contact","order"].includes(raw)?raw:"home"}
function navigate(view,updateHash=true){const target=view||"home";if(target===currentView&&document.querySelector(`.route-view[data-view="${target}"]`))return;if(updateHash&&location.hash!==`#${target}`)history.pushState(null,"",`#${target}`);$$('.route-view').forEach(v=>{v.hidden=v.dataset.view!==target});$$('[data-route]').forEach(a=>a.classList.toggle("active",a.dataset.route===target));currentView=target;window.scrollTo({top:0,behavior:reduceMotion?"auto":"smooth"});setTimeout(()=>{$("#app")?.focus({preventScroll:true});observeReveals(document.querySelector(`.route-view[data-view="${target}"]`));initHoverStates(document.querySelector(`.route-view[data-view="${target}"]`))},50)}
function initRouter(){window.addEventListener("hashchange",()=>navigate(routeFromHash(),false));navigate(routeFromHash(),false)}
function observeReveals(root=document){const els=$$('.reveal-up',root).filter(e=>!e.dataset.observed);if(reduceMotion||!("IntersectionObserver"in window)){els.forEach(e=>e.classList.add("is-visible"));return}const io=new IntersectionObserver(entries=>entries.forEach(en=>{if(en.isIntersecting){en.target.classList.add("is-visible");io.unobserve(en.target)}}),{threshold:.08,rootMargin:"0px 0px -7% 0px"});els.forEach(e=>{e.dataset.observed="1";io.observe(e)})}
function initCursor(){if(reduceMotion||!matchMedia("(pointer:fine)").matches)return;const dot=$(".cursor-dot"),ring=$(".cursor-ring");let x=-100,y=-100,rx=-100,ry=-100;addEventListener("pointermove",e=>{x=e.clientX;y=e.clientY;dot.style.transform=`translate3d(${x}px,${y}px,0)`});const loop=()=>{rx+=(x-rx)*.17;ry+=(y-ry)*.17;ring.style.transform=`translate3d(${rx}px,${ry}px,0)`;requestAnimationFrame(loop)};requestAnimationFrame(loop);initHoverStates(document)}
function initHoverStates(root=document){if(reduceMotion||!matchMedia("(pointer:fine)").matches)return;$$('a,button,.project-card,.contact-card',root).forEach(el=>{if(el.dataset.hoverBound)return;el.dataset.hoverBound="1";el.addEventListener("mouseenter",()=>$(".cursor-ring").classList.add(el.classList.contains("project-card")?"view":"link"));el.addEventListener("mouseleave",()=>$(".cursor-ring").classList.remove("view","link"))})}
function initMagnetic(){if(reduceMotion||!matchMedia("(pointer:fine)").matches)return;$$('.magnetic').forEach(el=>{el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect(),x=(e.clientX-(r.left+r.width/2))*.12,y=(e.clientY-(r.top+r.height/2))*.12;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener("pointerleave",()=>el.style.transform="")})}
function init(){initConfig();initDynamicContent();initFilters();renderProjects();initContact();initOrder();initHeader();initModal();initRouter();observeReveals();initCursor();initMagnetic()}
document.addEventListener("DOMContentLoaded",init);
